import { 
  CheckIcon, 
  ZapIcon, 
  DropletsIcon, 
  PaintRoller, 
  GripIcon, 
  FireExtinguisherIcon, 
  DoorClosedIcon, 
  SnowflakeIcon,
  FolderIcon,
  AirVentIcon,
  AlarmSmokeIcon,
  CheckCircleIcon,
  PackageIcon,
  BrickWallIcon,
  BrushIcon,
  ConstructionIcon,
  DropletOffIcon,
  DoorOpenIcon,
  TrendingUpIcon,
  FlameIcon,
  TrendingDownIcon,
  WifiIcon,
  AccessibilityIcon,
  AsteriskIcon,
  BadgeIcon,
  BanIcon,
  BlocksIcon,
  BoltIcon,
  BoxIcon,
  BoxesIcon,
  CarIcon,
  CctvIcon,
} from 'lucide-react';

export const categoriesIcons = {
  'unassigned': <CheckIcon className="text-muted-foreground h-4 w-4" />,
  'zap': <ZapIcon className="text-muted-foreground h-4 w-4" />,
  'droplets': <DropletsIcon className="text-muted-foreground h-4 w-4" />,
  'paint': <PaintRoller className="text-muted-foreground h-4 w-4" />,
  'carrelage': <GripIcon className="text-muted-foreground h-4 w-4" />,
  'fire-extinguisher': <FireExtinguisherIcon className="text-muted-foreground h-4 w-4" />,
  'doors': <DoorClosedIcon className="text-muted-foreground h-4 w-4" />,
  'snowflake': <SnowflakeIcon className="text-muted-foreground h-4 w-4" />,
  'folder': <FolderIcon className="text-muted-foreground h-4 w-4" />,
  'air-vent': <AirVentIcon className="text-muted-foreground h-4 w-4" />,
  'alarm-smoke': <AlarmSmokeIcon className="text-muted-foreground h-4 w-4" />,
  'check-circle': <CheckCircleIcon className="text-muted-foreground h-4 w-4" />,
  'package': <PackageIcon className="text-muted-foreground h-4 w-4" />,
  'brick-wall': <BrickWallIcon className="text-muted-foreground h-4 w-4" />,
  'brush-cleaning': <BrushIcon className="text-muted-foreground h-4 w-4" />,
  'construction': <ConstructionIcon className="text-muted-foreground h-4 w-4" />,
  'droplet-off': <DropletOffIcon className="text-muted-foreground h-4 w-4" />,
  'door-open': <DoorOpenIcon className="text-muted-foreground h-4 w-4" />,
  'trending-up': <TrendingUpIcon className="text-muted-foreground h-4 w-4" />,
  'flame': <FlameIcon className="text-muted-foreground h-4 w-4" />,
  'trending-down': <TrendingDownIcon className="text-muted-foreground h-4 w-4" />,
  'wifi': <WifiIcon className="text-muted-foreground h-4 w-4" />,
  'accessibility': <AccessibilityIcon className="text-muted-foreground h-4 w-4" />,
  'asterisk': <AsteriskIcon className="text-muted-foreground h-4 w-4" />,
  'badge': <BadgeIcon className="text-muted-foreground h-4 w-4" />,
  'ban': <BanIcon className="text-muted-foreground h-4 w-4" />,
  'blocks': <BlocksIcon className="text-muted-foreground h-4 w-4" />,
  'bolt': <BoltIcon className="text-muted-foreground h-4 w-4" />,
  'box': <BoxIcon className="text-muted-foreground h-4 w-4" />,
  'boxes': <BoxesIcon className="text-muted-foreground h-4 w-4" />,
  'car': <CarIcon className="text-muted-foreground h-4 w-4" />,
  'cctv': <CctvIcon className="text-muted-foreground h-4 w-4" />,
};

export const categoriesPinIcons = {
  unassigned: <CheckIcon className="text-white h-4 w-4" />,
  zap: <ZapIcon className="text-white h-4 w-4" />,
  droplets: <DropletsIcon className="text-white h-4 w-4" />,
  paint: <PaintRoller className="text-white h-4 w-4" />,
  carrelage: <GripIcon className="text-white h-4 w-4" />,
  snowflake: <SnowflakeIcon className="text-white h-4 w-4" />,
  "fire-extinguisher": <FireExtinguisherIcon className="text-white h-4 w-4" />,
  doors: <DoorClosedIcon className="text-white h-4 w-4" />,
  folder: <FolderIcon className="text-white h-4 w-4" />,
  "air-vent": <AirVentIcon className="text-white h-4 w-4" />,
  "alarm-smoke": <AlarmSmokeIcon className="text-white h-4 w-4" />,
  "check-circle": <CheckCircleIcon className="text-white h-4 w-4" />,
  package: <PackageIcon className="text-white h-4 w-4" />,
  "brick-wall": <BrickWallIcon className="text-white h-4 w-4" />,
  "brush-cleaning": <BrushIcon className="text-white h-4 w-4" />,
  construction: <ConstructionIcon className="text-white h-4 w-4" />,
  "droplet-off": <DropletOffIcon className="text-white h-4 w-4" />,
  "door-open": <DoorOpenIcon className="text-white h-4 w-4" />,
  "trending-up": <TrendingUpIcon className="text-white h-4 w-4" />,
  "flame": <FlameIcon className="text-white h-4 w-4" />,
  "trending-down": <TrendingDownIcon className="text-white h-4 w-4" />,
  "wifi": <WifiIcon className="text-white h-4 w-4" />,
  'accessibility': <AccessibilityIcon className="text-white h-4 w-4" />,
  'asterisk': <AsteriskIcon className="text-white h-4 w-4" />,
  'badge': <BadgeIcon className="text-white h-4 w-4" />,
  'ban': <BanIcon className="text-white h-4 w-4" />,
  'blocks': <BlocksIcon className="text-white h-4 w-4" />,
  'bolt': <BoltIcon className="text-white h-4 w-4" />,
  'box': <BoxIcon className="text-white h-4 w-4" />,
  'boxes': <BoxesIcon className="text-white h-4 w-4" />,
  'car': <CarIcon className="text-white h-4 w-4" />,
  'cctv': <CctvIcon className="text-white h-4 w-4" />,
};

